name: Setup strace logging
description: Creates a strace‑wrapped bash shell for all CI commands
author: clonedSemicolon

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        mkdir -p ci-bin strace_logs
        cat <<'EOF' > ci-bin/bash
        #!/bin/bash
        set -e
        cmd_hash=$(echo "$@" | sha1sum | awk '{print $1}')
        mkdir -p strace_logs
        sudo -E strace -tt -f -o strace_logs/step_${cmd_hash}.log /bin/bash "$@"
        EOF
        chmod +x ci-bin/bash
        echo "PATH=$GITHUB_WORKSPACE/ci-bin:$PATH" >> "$GITHUB_ENV"
